create table if not exists users (
    id integer primary key generated by default as identity,
    name varchar(50) unique not null,
    password varchar(50) not null,
    is_moderator boolean
);

create table if not exists spaceBodies(
    id integer primary key generated by default as identity,
    name varchar(50) not null,
    is_visible boolean
);

create table if not exists observations(
    id integer primary key generated by default as identity,
    space_body_id integer not null,
    user_id integer not null,
    foreign key (space_body_id) references spaceBodies(id),
    foreign key (user_id) references users(id),
    observation_time timestamp,
    declination float,
    ascension float,
    photo_url varchar(255)
);
