events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    gzip on;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;

    upstream backend {
        server 193.33.153.154:8080;
    }

    server {
        listen 80;
        server_name 193.33.153.154;
        root /site;
        index index.html index.htm;
        include /etc/nginx/mime.types;

        location /api {
            proxy_pass http://backend;
        }

        location ~ ^/(_app|_astro|favicon\.ico|robots\.txt|sitemap\.xml) {
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
